# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 235671245095dd200cb0b25c1d655bf594918a890536f8d16b3a1b4ec37a54eedd63b6892d387e1d8ee918af3634bfa06bb075741115cd528c5436f250e44046

test:
  secret_key_base: 8af653be916cb7c8d36858e4b589d5bdc7048f65ea110827af315832897336823efeef04882b11282dd62d0492c1763f9f4e2fd90785f2963e27c062a94ec033

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
